# Example requests

### Login 
POST http://localhost:3080/login
content-type: application/json

{
    "email": "Example item",
    "password": "This is an example item."
}

###
POST http://localhost:3080/register
content-type: application/json

{
    "fName": "Kieran", 
    "lName": "Allen", 
    "role": "admin", 
    "email": "kieranallen@gearworks.com", 
    "password": "kieallgwsw"
}